Wireframe, APIs, objects, Main Page & Pop-up features and functionalities implementation
alexansaa/Meals pull request #29
Opened 2023-08-10 22:40 UTC by alexansaa

In this milestone, the following features have been implemented:

The main page has been implemented showing a list of cards dynamically rendered, taking data from MealDB
The main page also is implementing like button functionality in order to preserve data with the Involvement API
Pop-up page has also been implemented when a card is clicked. This one lets the user comment and the comment data be preserved with Involvement API's help.
Comments in the Pop-up are rendered dynamically when a comment is posted and on Pop-up opens.
Meal object has been implemented. This object works as an interface between the APIs consumed and the web application. With the use of the web request custom library, the Meal class let us clear interoperation between APIs only with the use of objects of the class (idMeal field required for individual registry identification).
Like and Comment classes have also been defined in order to manage information properly.
Icons and styles have been implemented with respect to the wireframe given.

2023-08-10 23:11 UTC, anagudelogu requested changes
# STATUS:  CHANGES REQUIRED  ♻️ 🚧 

Hi @alexansaa, 
I'm Andres.


While you have done a great job working on this milestone 💻 , there are some issues that you still need to work on to go to the next project. ♻️ 

You are almost there, keep up the good work! 🚀 

<img src="https://media2.giphy.com/media/3ohhwi25ISXC7Z4tMs/giphy-downsized-medium.gif"/>

## Highlights
✅ Great use of Git flow. 💯 
✅ Your project is documented professionally. 📜 
✅ Descriptive PR title, summary and commit messages. 💬 

## Required Changes ♻️
_Check the comments under the review._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-10 23:11 UTC, anagudelogu commented on src/index.html
> +        </header>
- [ ] According to the requirements:

![image](https://github.com/alexansaa/Meals/assets/77069011/ef1b016b-74da-44a7-b208-c5399ca5ff58)

Please make sure to include functions for your counters. Currently, you haven't implemented any of them! 🤓 🔧 


Home page counter:
![image](https://github.com/alexansaa/Meals/assets/77069011/3a919cb5-9819-4568-a270-c8c5f73b6555)

Comments counter:
![image](https://github.com/alexansaa/Meals/assets/77069011/24bbab33-aa11-4497-af72-475ff66b99c6)

has a static `7`:
![image](https://github.com/alexansaa/Meals/assets/77069011/2dc3609a-1d9f-4f15-81e8-934dcf5c6117)

Please consider working on this, and don't forget to test them, this is another **important** requirement! 🤓 🔧

2023-08-10 23:11 UTC, anagudelogu commented on src/webRequest.js
> +  });
- [ ] Please consider refactoring this code to use ES6 features such as `async` and `await` instead of `.then().catch()` chains! 🤓 🔧

2023-08-11 04:45 UTC, MahmoudBakr23 requested changes
Hi @alexansaa 😃, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but some are still not been addressed yet.

> I'd like to remind you that your long hours of work are appreciated. However, the code review process is for improving the code you wrote, and not for criticizing it. 😄

 ## Required Changes ♻️

- [ ] Please consider writing unit tests for each of your functions. Currently, there are no more than 2 failed test suits!
![MINGW64__d_New folder_Meals_dist 8_11_2023 7_37_00 AM](https://github.com/alexansaa/Meals/assets/47625407/1fe6361f-2fbb-4fdd-95bd-208324ac4d4a)

_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better. Some of them were missed by the previous reviewer and addressing them will really improve your application._

N/A

Cheers and Happy coding!👏👨‍💻💻

Feel free to mention @MahmoudBakr23 to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-11 04:45 UTC, MahmoudBakr23 commented on server.js
> +});
- [ ] Please remove the `console` code as it is affecting performance and it's not code-related but debugging only 👍 see the hint [here](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md#:~:text=Do%20not%20commit%20console.log)

2023-08-11 04:45 UTC, MahmoudBakr23 commented on src/MealManager.js
> +      console.log(`GetLikes error: ${e}`);
- [ ] Please remove the `console` code as it is affecting performance and it's not code-related but debugging only 👍 see the hint [here](https://github.com/microverseinc/curriculum-html-css/blob/main/articles/javascript_best_practices.md#:~:text=Do%20not%20commit%20console.log)

2023-08-11 04:45 UTC, MahmoudBakr23 commented on README.md
> +- [Live Demo!](https://alexansaa.github.io/Meals/)
- [ ] Kindly make sure your live demo link is up-to-date with the latest changes in the app. Or remove its section from the README file for a professional repo. 🙏

2023-08-11 04:45 UTC, MahmoudBakr23 commented on src/MealManager.js
> +  }
- [ ] As requested by the previous reviewer, please make sure to show the number of items displayed on the home page. 🙏 
![Meals-Service](https://github.com/alexansaa/Meals/assets/47625407/3c92fae4-5860-4d02-8106-3588595533ec)

- [ ] Also, as per project requirements and the previous reviewer's suggestion, kindly refactor the fetching function into async await function. 👍

2023-08-11 15:05 UTC, joel-kalema requested changes
# STATUS: REQUIRED CHANGES :recycle::recycle: 

Hi @alexansaa 
Good job so far! I know you worked hard to implement this project, I really appreciate the effort you put in! But there are some issues that you still need to work on to go to the next project but you are almost there! 

![0bd223a2b156e0eaf61a713e84c3d3b7](https://user-images.githubusercontent.com/57408419/255594021-109e7375-12de-4f5b-9e29-79eefc52e35a.gif)



## To highlight :champagne: 

- Good commit history :heavy_check_mark: 
- Your design looks good :100: :heavy_check_mark: 
- Good PR description :heavy_check_mark: 
- Follow GitHub flow :heavy_check_mark: 

## Required changes :recycle: :recycle: 
- [ ] Check the comments under the review.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

_Feel free to leave any questions or comments in the PR thread if something is not 100% clear. 
Please ping me @joel-kalema  when you comment so I can receive the notification or use slack with the same name._

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-11 15:05 UTC, joel-kalema commented on src/MealManager.js
> +    const mealsRandArray = await Promise.all(mealPromises);
- [ ] Good job 🥇, however, as the previous reviewer said kindly refactor the fetching function into `async` `await` function 😄. It is not a good idea to `fetch` data in the `loop` function.

2023-08-11 16:56 UTC, usorfaitheloho approved these changes
Hi @alexansaa  , 
# STATUS: APPROVED! 🥇 💯 
![done](https://media.giphy.com/media/l1uga8ObPBnIBoXUQ/giphy.gif)

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-08-11 18:04 UTC, merged